version: '3.7'

services:
  fastapi:
    image: fastapi
    container_name: fastapi
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    command:
      - bash
      - -c
      - |
        while !</dev/tcp/postgres/5432; do sleep 1; done; mkdir /home/app/alembic/versions
        mkdir /home/app/logs
        alembic upgrade head
        uvicorn main:app --host 0.0.0.0 --reload
    ports:
      - "8000:8000"
    volumes:
      - "./app:/home/app"
    env_file: example.env
    depends_on:
      - postgres
    networks:
      - meetups_services
    restart: on-failure


  postgres:
    image: postgres:14
    container_name: postgres
    volumes:
      - ".data/postgres:/var/lib/postgresql/data"
    env_file: example.env
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    ports:
      - "5432:5432"
    networks:
      - meetups_services


networks:
  meetups_services:
    name: meetups_services
    driver: bridge