name: Checking code quality with Isort and Flake8

on:
  pull_request:
    branches:
      - main
      - master
      - develop

jobs:
  run_checker:
     runs-on: ubuntu-latest
     steps:
       - name: Setup Python
         uses: actions/setup-python@v1
         with:
           python-version: '3.10'
           architecture: 'x64'

       - name: Check out repo
         uses: actions/checkout@v2

       - name: Install requirements
         run: pip install -r requirements-ci.txt

       - name: Launch linter
         run: flake8 --exclude=app/alembic/ app/

#       - name: Launch imports checking
#         run: isort --check-only --diff ./app